INSERT INTO `airline` (id, code,`name`) VALUES (1,'UA','United Airlines');
INSERT INTO `airline` (id, code,`name`) VALUES (2,'DL','Delta Air Lines');
INSERT INTO `airline` (id, code,`name`) VALUES (3,'WN','Southwest Airlines');
INSERT INTO `airline` (id, code,`name`) VALUES (4,'TK','Turkish Airlines');
INSERT INTO `airline` (id, code,`name`) VALUES (5,'AA','American Airlines');
INSERT INTO `airline` (id, code,`name`) VALUES (6,'AS','Alaska Airlines');
INSERT INTO `airline` (id, code,`name`) VALUES (7,'B6','JetBlue Airways');
INSERT INTO `airline` (id, code,`name`) VALUES (8,'XB','Air Canada');
INSERT INTO `airline` (id, code,`name`) VALUES (9,'NK','Spirit Airlines');
INSERT INTO `airline` (id, code,`name`) VALUES (10,'HA','Hawaiian Airlines');
INSERT INTO `airline` (id, code,`name`) VALUES (11,'QR','4D Air');
INSERT INTO `airline` (id, code,`name`) VALUES (12,'TH','611897 Alberta Limited');
INSERT INTO `airline` (id, code,`name`) VALUES (13,'AA','Ansett Australia');
INSERT INTO `airline` (id, code,`name`) VALUES (14,'AI','Abacus International');
INSERT INTO `airline` (id, code,`name`) VALUES (15,'A2','Abelag Aviation');
INSERT INTO `airline` (id, code,`name`) VALUES (16,'AA','Army Air Corps');
INSERT INTO `airline` (id, code,`name`) VALUES (17,'A3','Aero Aviation Centre Ltd.');
INSERT INTO `airline` (id, code,`name`) VALUES (18,'SI','Aero Servicios Ejecutivos Internacionales');
INSERT INTO `airline` (id, code,`name`) VALUES (19,'BZ','Aero Biniza');

INSERT INTO history (history,id) VALUES ('UAL Corporation is the holding company for United Airlines, Inc., the world''s largest airline, which flies 240,000 passengers a day to 26 countries.',1);
INSERT INTO history (history,id) VALUES ('Delta Air Lines, Inc. is one of the largest and most successful air carriers in the United States. Originally founded as a crop dusting service in 1924, Delta was led for 40 years by an agricultural scientist and pilot named Collet Everman Woolman.',2);
INSERT INTO history (history,id) VALUES ('Southwest Airlines Co. is a major U.S. airline and considered as the world’s largest low-cost carrier. The main office of Southwest Airlines Co. is located in Dallas, Texas.',3);
INSERT INTO history (history,id) VALUES ('Back in 1933, the Turkish Airlines adventure began; an endeavor to unite people, cultures, continents, countries and cities whilst providing new, inspiring travel experiences for all. On the 20th of May 1933, we took to the skies as State Airlines Administration.',4);
INSERT INTO history (history,id) VALUES ('American Airlines is a product of the merger of a number of small airline companies. One of these founding enterprises was the Robertson Aircraft Company of Missouri, which employed Charles Lindbergh to pilot its first airmail run in 1926.',5);
INSERT INTO history (history,id) VALUES ('Alaska Air Group, Inc. is the holding company for Alaska Air, the tenth largest U.S. airline with the country''s youngest fleet of aircraft.',6);
INSERT INTO history (history,id) VALUES ('JetBlue, the John F. Kennedy airport New York-based low-cost carrier, was founded by David Neeleman and began operations in February 2000.',7);
INSERT INTO history (history,id) VALUES ('Air Canada is the only national, full-service airline based in Canada.',8);
INSERT INTO history (history,id) VALUES ('Travel Agent magazine calls Spirit Airlines, Inc. ''the most successful small carrier you''ve never heard of.',9);
INSERT INTO history (history,id) VALUES ('Hawaiian Airlines, Inc. flies between the Hawaiian Islands, several cities in the western U.S. mainland and South Pacific destinations.',10);
INSERT INTO history (history,id) VALUES ('Started in 1970',11);
INSERT INTO history (history,id) VALUES ('Started in 1988',12);
INSERT INTO history (history,id) VALUES ('Started in 1955',13);
INSERT INTO history (history,id) VALUES ('Started in 1945',14);
INSERT INTO history (history,id) VALUES ('Started in 1995',15);
INSERT INTO history (history,id) VALUES ('Started in 1993',16);
INSERT INTO history (history,id) VALUES ('Started in 1997',17);
INSERT INTO history (history,id) VALUES ('Started in 1999',18);
INSERT INTO history (history,id) VALUES ('Started in 1985',19);

INSERT INTO `airport` (id, code, name, city,state,street,zip) VALUES (1,  'SFO', 'San-Francisco-International', 'San-Francisco', 'CA', '', '234');
INSERT INTO `airport` (id, code, name, city,state,street,zip) VALUES (2,  'OAK', 'Oakland-International', 'Oakland', 'CA', '', '456');
INSERT INTO `airport` (id, code, name, city,state,street,zip) VALUES (3,  'LAS', 'McCarren-International', 'Las-Vegas', 'NV', '', '456');
INSERT INTO `airport` (id, code, name, city,state,street,zip) VALUES (4,  'HNL', 'Honolulu-International', 'Honolulu', 'HI', '', '456');
INSERT INTO `airport` (id, code, name, city,state,street,zip) VALUES (5,  'JFK', 'John-F-Kennedy-International', 'New-York', 'NY', '', '456');
INSERT INTO `airport` (id, code, name, city,state,street,zip) VALUES (6,  'FAT', 'Fresno-Yosemite-International', 'Fresno', 'CA', '', '456');
INSERT INTO `airport` (id, code, name, city,state,street,zip) VALUES (7,  'MSY', 'Louis-Armstrong', 'New-Orleans', 'LA', '', '456');
INSERT INTO `airport` (id, code, name, city,state,street,zip) VALUES (8,  'ORD', 'Chicago-OHare-International', 'Chicago', 'IL', '', '456');
INSERT INTO `airport` (id, code, name, city,state,street,zip) VALUES (9,  'MDW', 'Midway', 'Chicago', 'IL', '', '456');
INSERT INTO `airport` (id, code, name, city,state,street,zip) VALUES (10, 'SMF', 'Sacramento-International', 'Sacramento', 'CA', '', '456');
INSERT INTO `airport` (id, code, name, city,state,street,zip) VALUES (11, 'SCK', 'Stockton-Metropolitan', 'Stockton', 'CA', '', '456');
INSERT INTO `airport` (id, code, name, city,state,street,zip) VALUES (12, 'PHX', 'Phoenix-Sky-Harbor', 'Phoenix', 'AZ', '', '456');
INSERT INTO `airport` (id, code, name, city,state,street,zip) VALUES (13, 'DEN', 'Denver-International', 'Denver', 'CO', '', '456');
INSERT INTO `airport` (id, code, name, city,state,street,zip) VALUES (14, 'EWR', 'Newark-International', 'Newark', 'NJ', '', '456');
INSERT INTO `airport` (id, code, name, city,state,street,zip) VALUES (15, 'IAH', 'Bush-Intercontinental', 'Houston', 'TX', '', '456');
INSERT INTO `airport` (id, code, name, city,state,street,zip) VALUES (16, 'LAX', 'Los-Angeles-International', 'Los-Angeles', 'CA', '', '456');
INSERT INTO `airport` (id, code, name, city,state,street,zip) VALUES (17, 'DCA', 'Ronald-Reagan-National', 'Arlington', 'VA', '', '456');
INSERT INTO `airport` (id, code, name, city,state,street,zip) VALUES (18, 'IAD', 'Washington-Dulles-International', 'Dulles', 'VA', '', '456');
INSERT INTO `airport` (id, code, name, city,state,street,zip) VALUES (19, 'SLC', 'Salt-Lake-City-International', 'Salt-Lake-City', 'UT', '', '456');
INSERT INTO `airport` (id, code, name, city,state,street,zip) VALUES (20, 'DFW', 'Dallas-Fort-Worth', 'DFW', 'TX', '', '456');

